export const bonus = {
  '1': {
    bonus1: { order: 7, description: 'Give Sadaqah (Charity)' },
    bonus2: { order: 8, description: 'Memorize Quran or Duas' },
    bonus3: { order: 9, description: 'Prepare or Distribute Iftar' },
    bonus4: { order: 10, description: 'Volunteer in the Community' },
    bonus5: { order: 11, description: 'Spend Quality Time with Family' },
    bonus6: { order: 12, description: 'Memorize Quran or Duas' },
    bonus7: { order: 13, description: 'Prepare or Distribute Iftar' },
  },
  '2': {
    bonus1: { order: 7, description: 'Memorize Quran or Duas' },
    bonus2: { order: 8, description: 'Volunteer in the Community' },
    bonus3: { order: 9, description: 'Give Sadaqah (Charity)' },
    bonus4: { order: 10, description: 'Spend Quality Time with Family' },
    bonus5: { order: 11, description: 'Prepare or Distribute Iftar' },
    bonus6: { order: 12, description: 'Spend Quality Time with Family' },
    bonus7: { order: 13, description: 'Volunteer in the Community' },
  },
  '3': {
    bonus1: { order: 7, description: 'Prepare or Distribute Iftar' },
    bonus2: { order: 8, description: 'Memorize Quran or Duas' },
    bonus3: { order: 9, description: 'Volunteer in the Community' },
    bonus4: { order: 10, description: 'Give Sadaqah (Charity)' },
    bonus5: { order: 11, description: 'Spend Quality Time with Family' },
    bonus6: { order: 12, description: 'Prepare or Distribute Iftar' },
    bonus7: { order: 13, description: 'Memorize Quran or Duas' },
  },
  '4': {
    bonus1: { order: 7, description: 'Spend Quality Time with Family' },
    bonus2: { order: 8, description: 'Give Sadaqah (Charity)' },
    bonus3: { order: 9, description: 'Prepare or Distribute Iftar' },
    bonus4: { order: 10, description: 'Memorize Quran or Duas' },
    bonus5: { order: 11, description: 'Volunteer in the Community' },
    bonus6: { order: 12, description: 'Spend Quality Time with Family' },
    bonus7: { order: 13, description: 'Memorize Quran or Duas' },
  },
  '5': {
    bonus1: { order: 7, description: 'Volunteer in the Community' },
    bonus2: { order: 8, description: 'Prepare or Distribute Iftar' },
    bonus3: { order: 9, description: 'Give Sadaqah (Charity)' },
    bonus4: { order: 10, description: 'Memorize Quran or Duas' },
    bonus5: { order: 11, description: 'Spend Quality Time with Family' },
    bonus6: { order: 12, description: 'Spend Quality Time with Family' },
    bonus7: { order: 13, description: 'Give Sadaqah (Charity)' },
  },
  '6': {
    bonus1: { order: 7, description: 'Memorize Quran or Duas' },
    bonus2: { order: 8, description: 'Prepare or Distribute Iftar' },
    bonus3: { order: 9, description: 'Spend Quality Time with Family' },
    bonus4: { order: 10, description: 'Volunteer in the Community' },
    bonus5: { order: 11, description: 'Give Sadaqah (Charity)' },
    bonus6: { order: 12, description: 'Spend Quality Time with Family' },
    bonus7: { order: 13, description: 'Memorize Quran or Duas' },
  },
  '7': {
    bonus1: { order: 7, description: 'Give Sadaqah (Charity)' },
    bonus2: { order: 8, description: 'Memorize Quran or Duas' },
    bonus3: { order: 9, description: 'Prepare or Distribute Iftar' },
    bonus4: { order: 10, description: 'Volunteer in the Community' },
    bonus5: { order: 11, description: 'Spend Quality Time with Family' },
    bonus6: { order: 12, description: 'Memorize Quran or Duas' },
    bonus7: { order: 13, description: 'Prepare or Distribute Iftar' },
  },
  '8': {
    bonus1: { order: 7, description: 'Prepare or Distribute Iftar' },
    bonus2: { order: 8, description: 'Give Sadaqah (Charity)' },
    bonus3: { order: 9, description: 'Memorize Quran or Duas' },
    bonus4: { order: 10, description: 'Volunteer in the Community' },
    bonus5: { order: 11, description: 'Spend Quality Time with Family' },
    bonus6: { order: 12, description: 'Give Sadaqah (Charity)' },
    bonus7: { order: 13, description: 'Volunteer in the Community' },
  },
  '9': {
    bonus1: { order: 7, description: 'Spend Quality Time with Family' },
    bonus2: { order: 8, description: 'Give Sadaqah (Charity)' },
    bonus3: { order: 9, description: 'Memorize Quran or Duas' },
    bonus4: { order: 10, description: 'Prepare or Distribute Iftar' },
    bonus5: { order: 11, description: 'Volunteer in the Community' },
    bonus6: { order: 12, description: 'Memorize Quran or Duas' },
    bonus7: { order: 13, description: 'Prepare or Distribute Iftar' },
  },
  '10': {
    bonus1: { order: 7, description: 'Give Sadaqah (Charity)' },
    bonus2: { order: 8, description: 'Memorize Quran or Duas' },
    bonus3: { order: 9, description: 'Volunteer in the Community' },
    bonus4: { order: 10, description: 'Spend Quality Time with Family' },
    bonus5: { order: 11, description: 'Prepare or Distribute Iftar' },
    bonus6: { order: 12, description: 'Memorize Quran or Duas' },
    bonus7: { order: 13, description: 'Give Sadaqah (Charity)' },
  },
}
