export default {
  'en-US': [
    'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'I seek refuge in You from the accursed Satan, and from all evil deeds that may harm me...',
    'To You belong the East and the West: here I come to You as a supplicant...',
    'Lord of the universe, You are the Most Merciful, the Most Compassionate. Have mercy on me, O Lord...',
    'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
    'You are the One who has created all things from nothing, and I am but a small creature in Your sight. Have mercy on me, O Lord...',
    'O Allah, You are the Most Forgiving, the Most Merciful. Forgive my sins and grant me forgiveness...',
    'I seek Your pardon for my mistakes and transgressions. Guide me to the right path and show me the way of righteousness.',
    'You are the One who has sent prophets upon the world, and I am but a lowly servant. Show me the truth and guide me on the right path...',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'I seek Your forgiveness for my sins and transgressions. Guide me to the right path and show me the way of righteousness.',
    'O Allah, You are the Most Merciful, the Most Compassionate. Have mercy on me, O Lord...',
    'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
    'I seek refuge in You from all evil deeds that may harm me, O Allah...',
    'To You belong the Night and the Day: here I come to You as a supplicant...',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'O Allah, grant me wisdom and knowledge during this blessed month of Ramadan...',
    'You are the One who has created all things from nothing, and I am but a small creature in Your sight. Have mercy on me, O Lord...',
    'I seek Your pardon for my mistakes and transgressions. Guide me to the right path and show me the way of righteousness.',
    'O Allah, You are the Most Forgiving, the Most Merciful. Forgive my sins and grant me forgiveness...',
    'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
    'I seek refuge in You from all evil deeds that may harm me, O Allah...',
    'To You belong the Night and the Day: here I come to You as a supplicant...',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'O Allah, grant me strength and courage during this blessed month of Ramadan...',
    'You are the One who has sent prophets upon the world, and I am but a lowly servant. Show me the truth and guide me on the right path...',
    'I seek Your forgiveness for my sins and transgressions. Guide me to the right path and show me the way of righteousness.',
    'O Allah, You are the Most Merciful, the Most Compassionate. Have mercy on me, O Lord...',
    'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
    'I seek refuge in You from all evil deeds that may harm me, O Allah...',
    'To You belong the Night and the Day: here I come to You as a supplicant...',
    'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
    'O Allah, grant me wisdom and knowledge during this blessed month of Ramadan...',
    'You are the One who has created all things from nothing, and I am but a small creature in Your sight. Have mercy on me, O Lord...',
  ],
  'ar-SA': [
    'اللهم امنحني الصبر والهداية في هذا الشهر المبارك من رمضان...',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'أستعيذ بك من الشيطان الرجيم، ومن جميع الأعمال الشريرة التي قد تضر بي...',
    'لك المشرق والمغرب: إليك أتوجه طالباً...',
    'رب السماوات والأرض، أنت الأرحم، الرحيم. ارحمنا يا رب...',
    'أعلن عبوديتى لك يا الله، واعتمادي عليك. أرحمني وهدني إلى الطريق المستقيم.',
    'أنت الذي خلقت كل شيء من لا شيء، وأنا مجرد مخلوق صغير في نظرك. ارحمني يا رب...',
    'اللهم أنت الغفور الرحيم. اغفر لي ذنوبي وامنحني المغفرة...',
    'أطلب عفوك عن أخطائي وتجاوزاتي. اهدني إلى الطريق المستقيم وعلمني طريق البر.',
    'أنت الذي أرسلت الأنبياء إلى العالم، وأنا مجرد عبد ذليل. أرني الحق واهدني إلى الطريق المستقيم...',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'أطلب مغفرتك عن ذنوبي وتجاوزاتي. اهدني إلى الطريق المستقيم وعلمني طريق البر.',
    'اللهم أنت الأرحم، الرحيم. ارحمنا يا رب...',
    'أعلن عبوديتى لك يا الله، واعتمادي عليك. أرحمني وهدني إلى الطريق المستقيم.',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'اللهم امنحني الصبر والهداية في هذا الشهر المبارك من رمضان...',
    'أستعيذ بك من جميع الأعمال الشريرة التي قد تضر بي، يا الله...',
    'لك الليل والنهار: إليك أتوجه طالباً...',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'اللهم امنحني الحكمة والعلم في هذا الشهر المبارك من رمضان...',
    'أنت الذي خلقت كل شيء من لا شيء، وأنا مجرد مخلوق صغير في نظرك. ارحمني يا رب...',
    'أطلب عفوك عن أخطائي وتجاوزاتي. اهدني إلى الطريق المستقيم وعلمني طريق البر.',
    'اللهم أنت الغفور الرحيم. اغفر لي ذنوبي وامنحني المغفرة...',
    'أعلن عبوديتى لك يا الله، واعتمادي عليك. أرحمني وهدني إلى الطريق المستقيم.',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'اللهم امنحني الصبر والهداية في هذا الشهر المبارك من رمضان...',
    'أستعيذ بك من جميع الأعمال الشريرة التي قد تضر بي، يا الله...',
    'لك الليل والنهار: إليك أتوجه طالباً...',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'اللهم امنحني القوة والشجاعة في هذا الشهر المبارك من رمضان...',
    'أنت الذي أرسلت الأنبياء إلى العالم، وأنا مجرد عبد ذليل. أرني الحق واهدني إلى الطريق المستقيم...',
    'أطلب مغفرتك عن ذنوبي وتجاوزاتي. اهدني إلى الطريق المستقيم وعلمني طريق البر.',
    'اللهم أنت الأرحم، الرحيم. ارحمنا يا رب...',
    'أعلن عبوديتى لك يا الله، واعتمادي عليك. أرحمني وهدني إلى الطريق المستقيم.',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'اللهم امنحني الصبر والهداية في هذا الشهر المبارك من رمضان...',
    'أستعيذ بك من جميع الأعمال الشريرة التي قد تضر بي، يا الله...',
    'لك الليل والنهار: إليك أتوجه طالباً...',
    'الله أكبر، وأنا عبد فقير. تقبل توبتي واغفر لي...',
    'اللهم امنحني الحكمة والعلم في هذا الشهر المبارك من رمضان...',
    'أنت الذي خلقت كل شيء من لا شيء، وأنا مجرد مخلوق صغير في نظرك. ارحمني يا رب...',
  ],
} as Duaa

type Duaa = {
  [key: string]: string[]
}
