export default [
  'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'I seek refuge in You from the accursed Satan, and from all evil deeds that may harm me...',
  'To You belong the East and the West: here I come to You as a supplicant...',
  'Lord of the universe, You are the Most Merciful, the Most Compassionate. Have mercy on me, O Lord...',
  'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
  'You are the One who has created all things from nothing, and I am but a small creature in Your sight. Have mercy on me, O Lord...',
  'O Allah, You are the Most Forgiving, the Most Merciful. Forgive my sins and grant me forgiveness...',
  'I seek Your pardon for my mistakes and transgressions. Guide me to the right path and show me the way of righteousness.',
  'You are the One who has sent prophets upon the world, and I am but a lowly servant. Show me the truth and guide me on the right path...',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'I seek Your forgiveness for my sins and transgressions. Guide me to the right path and show me the way of righteousness.',
  'O Allah, You are the Most Merciful, the Most Compassionate. Have mercy on me, O Lord...',
  'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
  'I seek refuge in You from all evil deeds that may harm me, O Allah...',
  'To You belong the Night and the Day: here I come to You as a supplicant...',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'O Allah, grant me wisdom and knowledge during this blessed month of Ramadan...',
  'You are the One who has created all things from nothing, and I am but a small creature in Your sight. Have mercy on me, O Lord...',
  'I seek Your pardon for my mistakes and transgressions. Guide me to the right path and show me the way of righteousness.',
  'O Allah, You are the Most Forgiving, the Most Merciful. Forgive my sins and grant me forgiveness...',
  'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
  'I seek refuge in You from all evil deeds that may harm me, O Allah...',
  'To You belong the Night and the Day: here I come to You as a supplicant...',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'O Allah, grant me strength and courage during this blessed month of Ramadan...',
  'You are the One who has sent prophets upon the world, and I am but a lowly servant. Show me the truth and guide me on the right path...',
  'I seek Your forgiveness for my sins and transgressions. Guide me to the right path and show me the way of righteousness.',
  'O Allah, You are the Most Merciful, the Most Compassionate. Have mercy on me, O Lord...',
  'I declare my servitude to You, O Allah, and my dependence upon You. Show me Your mercy and guide me on the right path.',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'O Allah, grant me patience and guidance during this blessed month of Ramadan...',
  'I seek refuge in You from all evil deeds that may harm me, O Allah...',
  'To You belong the Night and the Day: here I come to You as a supplicant...',
  'Allah is the greatest, and I am but a poor slave. Accept my repentance and forgive me...',
  'O Allah, grant me wisdom and knowledge during this blessed month of Ramadan...',
  'You are the One who has created all things from nothing, and I am but a small creature in Your sight. Have mercy on me, O Lord...',
]
